### ISSUE TITLE
TCPEndpoint not offering IoFilterChainBuilder

### ISSUE THREAD

**Issue by enexusde** [apache/mina-vysper#13]
```
TCPEndpoint endpoint = new TCPEndpointChainBuilder();
server = new XMPPServer(serverName);
server.addEndpoint(endpoint);
server.start();
endpoint.getFilterChainBuilder().addFirst("custom", new MyCustomFilter());
```
Always throw a NPE because the field `filterChainBuilder` in `TCPEndpoint` is never written.

**Comment by enexusde** [comment]
I think you could fix this by adding 
````
this.filterChainBuilder = filterChainBuilder;
````

to the `start` method.

**Comment by reda-alaoui** [comment]
Please contribute with a pull request

**Comment by enexusde** [comment]
Resolved by https://github.com/apache/mina-vysper/commit/dbfedf822349f53e1848297145634079b204988f?branch=dbfedf822349f53e1848297145634079b204988f&diff=unified
